//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeViever.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.DepartmentCompanies = new HashSet<DepartmentCompany>();
            this.PersonDepartments = new HashSet<PersonDepartment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ParentDepartmentID { get; set; }
    
        public virtual ICollection<DepartmentCompany> DepartmentCompanies { get; set; }
        public virtual ICollection<PersonDepartment> PersonDepartments { get; set; }
    }
}
