//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeViever.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCard
    {
        public int ID { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public System.DateTime DateValid { get; set; }
        public int CardID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Card Card { get; set; }
    }
}
