//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeViever.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentCompany
    {
        public int Id { get; set; }
        public int DepartmentID { get; set; }
        public int CompanyID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Company Company { get; set; }
    }
}
