//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeViever.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonCards = new HashSet<PersonCard>();
            this.PersonDepartments = new HashSet<PersonDepartment>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EMB { get; set; }
    
        public virtual ICollection<PersonCard> PersonCards { get; set; }
        public virtual ICollection<PersonDepartment> PersonDepartments { get; set; }
    }
}
